@startuml
actor User

cloud AWS {
    node WMB
    database Redis
    node CS
}

cloud Google {
    node Firebase
}

cloud Atlas {
    database Mongo
}

cloud GAE{
    node ID
}

User -- WMB
User -- Firebase

WMB -- ID
WMB -- CS
WMB -- Mongo
WMB -- Redis
WMB -- Firebase

@enduml
